### ISSUE TITLE
Support for integration with issuer service via QR code

### ISSUE THREAD

**Issue by kskaret** [eu-digital-identity-wallet/eudi-app-ios-wallet-ui#65]
As of now, the reference implementation of the wallet only supports retrieving the two specific credentials, National ID and Driving Licence, from one hardcoded issuer service.
Is there a plan to add support for integration with other arbitrary issuer services?
As with this service, for example, https://issuer-backend.eudiw.dev/issuer/credentialsOffer/generate
It does have the functionality to display a QR code, but as far as we can see, there is no support for scanning this with the wallet now.
<img width="1393" alt="image" src="https://github.com/eu-digital-identity-wallet/eudi-app-ios-wallet-ui/assets/1201673/e187af09-bf20-45df-9df9-fcd72b31b115">

**Comment by stzouvaras** [comment]
Hello @kskaret 

This feature is already on our backlog.

**Comment by kskaret** [comment]
Thanks @stzouvaras, that's good to know. 
Is it possible to estimate a timeframe for when such support can be available?

The reason why I’m asking is because we have been working on adding support for the reference implementation wallet to our issuer service.

Now we have got a working prototype, but while waiting for QR-code support, our workaround is to change the hardcoded issuer service URL in the project (VCI_ISSUER_URL) to point directly to our service.

By the way, here is a quick demo of the EUDI wallet integrated with our prototype of a Norwegian PID issuer.

https://github.com/eu-digital-identity-wallet/eudi-app-ios-wallet-ui/assets/1201673/faa55879-3644-4c2e-9804-74c62e89448a

**Comment by stzouvaras** [comment]
Hi @kskaret,

we are working on it, the plan is to release the ecosystem and the apps to support the Draft 13 issuer and credential offer by the end of June.

For the iOS wallet, you can follow these 2 issues:
- https://github.com/eu-digital-identity-wallet/eudi-app-ios-wallet-ui/issues/75
- https://github.com/eu-digital-identity-wallet/eudi-app-ios-wallet-ui/issues/76
